version: "3.8"
services:
    nodeserver:
        restart: unless-stopped
        build:
            context: ./node
            dockerfile: Dockerfile
        image: nodeserver
        container_name: nodeserver
        ports:
            - "3000:3000"
        networks:
            - app_network

    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes: 
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./web/src:/usr/share/nginx
            - ./nginx/certbot-var:/var/lib/letsencrypt
        networks:
            - app_network
    
networks:
    app_network:
        driver: bridge